// Code generated by Kubeform. DO NOT EDIT.

package main

import (
	"github.com/spf13/cobra"
	v "gomodules.xyz/x/version"
	"kmodules.xyz/client-go/tools/cli"
)

func NewRootCmd(version string) *cobra.Command {
	var rootCmd = &cobra.Command{
		Use:               "provider-linode-controller",
		DisableAutoGenTag: true,
		PersistentPreRun: func(c *cobra.Command, args []string) {
			cli.SendAnalytics(c, version)
		},
	}
	rootCmd.PersistentFlags().BoolVar(&cli.EnableAnalytics, "enable-analytics", cli.EnableAnalytics, "Send analytical events to Google Analytics")

	rootCmd.AddCommand(v.NewCmdVersion())
	rootCmd.AddCommand(NewCmdRun(version))

	return rootCmd
}
